### ISSUE TITLE
Branch Check

### ISSUE THREAD

**Issue by 0xgdr** [WashDesign/Wash-Site#3]
@ewe1991 just checking that the main branch for this is the master branch? I have created a branch off master and added Craft, so any changes you make would need to be pushed to the master branch, are you o.k. with that? Eventually everything will get pushed to master when we go live.

**Comment by ewe1991** [comment]
The branch I've been working on is static site, have not pushed to the
master yet. I would just look at that and see if master is the same. Not
sure if Lewis pushed his changes to master either.

On Saturday, May 10, 2014, Gareth Redfern notifications@github.com wrote:

> @ewe1991 https://github.com/ewe1991 just checking that the main branch
> for this is the master branch? I have created a branch off master and added
> Craft, so any changes you make would need to be pushed to the master
> branch, are you o.k. with that? Eventually everything will get pushed to
> master when we go live.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/WashDesign/Wash-Site/issues/3
> .

## 

## 

Elliott Evans
weare_bold_

_-_

This email is intended for use by the addrese(s) only. If you have received
this in error, do not disclose or retain it but delete it immediately and
advise the sender that you have received it in error.

**Comment by 0xgdr** [comment]
I have merged the static site branch into master, everything seems to have merged correctly.
